/**
 * TinyAVRLib/Soundlib - Testing melody
 * @author Neven Boyanov
 * This is part of the Tinusaur/TinyAVRLib project.
 * ----------------------------------------------------------------------------
 *  Copyright (c) 2021 Tinusaur (https://tinusaur.com). All rights reserved.
 *  Distributed as open source under the MIT License (see the LICENSE.txt file)
 *  Please, retain in your work a link to the Tinusaur project website.
 * ----------------------------------------------------------------------------
 * Source code available at: https://gitlab.com/tinusaur/tinyavrlib
 */

// ----------------------------------------------------------------------------

#ifndef PRELUDE_IN_C_H
#define PRELUDE_IN_C_H

// ----------------------------------------------------------------------------

#include <avr/pgmspace.h>

#include "tinyavrlib/soundlib.h"
#include "tinyavrlib/soundlib_notes.h"

// ----------------------------------------------------------------------------

/**
 * "Prelude in C" Well-Tempered Clavier, J.S.Bach
 * Ref.: http://w8bh.net/avr/TrinketTone.pdf
 */

soundlib_melody_data_t prelude_in_c_notes[] PROGMEM = {
	NOTE_C4N, NOTE_E4N, NOTE_G4N, NOTE_C5N, NOTE_E5N, NOTE_G4N, NOTE_C5N, NOTE_E5N, //measures 1-2, NOTE_notes 1-32
	NOTE_C4N, NOTE_E4N, NOTE_G4N, NOTE_C5N, NOTE_E5N, NOTE_G4N, NOTE_C5N, NOTE_E5N,
	NOTE_C4N, NOTE_D4N, NOTE_A4N, NOTE_D5N, NOTE_F5N, NOTE_A4N, NOTE_D5N, NOTE_F5N,
	NOTE_C4N, NOTE_D4N, NOTE_A4N, NOTE_D5N, NOTE_F5N, NOTE_A4N, NOTE_D5N, NOTE_F5N,
	NOTE_B3N, NOTE_D4N, NOTE_G4N, NOTE_D5N, NOTE_F5N, NOTE_G4N, NOTE_D5N, NOTE_F5N, // measures 3-4, NOTE_notes 33-64
	NOTE_B3N, NOTE_D4N, NOTE_G4N, NOTE_D5N, NOTE_F5N, NOTE_G4N, NOTE_D5N, NOTE_F5N,
	NOTE_C4N, NOTE_E4N, NOTE_G4N, NOTE_C5N, NOTE_E5N, NOTE_G4N, NOTE_C5N, NOTE_E5N,
	NOTE_C4N, NOTE_E4N, NOTE_G4N, NOTE_C5N, NOTE_E5N, NOTE_G4N, NOTE_C5N, NOTE_E5N,

	NOTE_C4N, NOTE_E4N, NOTE_A4N, NOTE_E5N, NOTE_A5N, NOTE_A4N, NOTE_E5N, NOTE_A5N, // measures 5-6, NOTE_notes 65-96
	NOTE_C4N, NOTE_E4N, NOTE_A4N, NOTE_E5N, NOTE_A5N, NOTE_A4N, NOTE_E5N, NOTE_A5N,
	NOTE_C4N, NOTE_D4N, NOTE_F4S, NOTE_A4N, NOTE_D5N, NOTE_F4S, NOTE_A4N, NOTE_D5N,
	NOTE_C4N, NOTE_D4N, NOTE_F4S, NOTE_A4N, NOTE_D5N, NOTE_F4S, NOTE_A4N, NOTE_D5N,

	NOTE_B3N, NOTE_D4N, NOTE_G4N, NOTE_D5N, NOTE_G5N, NOTE_G4N, NOTE_D5N, NOTE_G5N, // measures 7-8, NOTE_notes 97-128
	NOTE_B3N, NOTE_D4N, NOTE_G4N, NOTE_D5N, NOTE_G5N, NOTE_G4N, NOTE_D5N, NOTE_G5N,
	NOTE_B3N, NOTE_C4N, NOTE_E4N, NOTE_G4N, NOTE_C5N, NOTE_E4N, NOTE_G4N, NOTE_C5N,
	NOTE_B3N, NOTE_C4N, NOTE_E4N, NOTE_G4N, NOTE_C5N, NOTE_E4N, NOTE_G4N, NOTE_C5N,

	NOTE_A3N, NOTE_C4N, NOTE_E4N, NOTE_G4N, NOTE_C5N, NOTE_E4N, NOTE_G4N, NOTE_C5N, // measures 9-10, NOTE_notes 129-160
	NOTE_A3N, NOTE_C4N, NOTE_E4N, NOTE_G4N, NOTE_C5N, NOTE_E4N, NOTE_G4N, NOTE_C5N,
	NOTE_D3N, NOTE_A3N, NOTE_D4N, NOTE_F4S, NOTE_C5N, NOTE_D4N, NOTE_F4S, NOTE_C5N,
	NOTE_D3N, NOTE_A3N, NOTE_D4N, NOTE_F4S, NOTE_C5N, NOTE_D4N, NOTE_F4S, NOTE_C5N,

	NOTE_G3N, NOTE_B3N, NOTE_D4N, NOTE_G4N, NOTE_B4N, NOTE_D4N, NOTE_G4N, NOTE_B4N, // measures 11-12, NOTE_notes 161-192
	NOTE_G3N, NOTE_B3N, NOTE_D4N, NOTE_G4N, NOTE_B4N, NOTE_D4N, NOTE_G4N, NOTE_B4N,
	NOTE_G3N, NOTE_A3S, NOTE_E4N, NOTE_G4N, NOTE_C5S, NOTE_E4N, NOTE_G4N, NOTE_C5S,
	NOTE_G3N, NOTE_A3S, NOTE_E4N, NOTE_G4N, NOTE_C5S, NOTE_E4N, NOTE_G4N, NOTE_C5S,
	NOTE_F3N, NOTE_A3N, NOTE_D4N, NOTE_A4N, NOTE_D5N, NOTE_D4N, NOTE_A4N, NOTE_D5N, // measures 13-14, NOTE_notes 193-224
	NOTE_F3N, NOTE_A3N, NOTE_D4N, NOTE_A4N, NOTE_D5N, NOTE_D4N, NOTE_A4N, NOTE_D5N,
	NOTE_F3N, NOTE_G3S, NOTE_D4N, NOTE_F4N, NOTE_B4N, NOTE_D4N, NOTE_F4N, NOTE_B4N,
	NOTE_F3N, NOTE_G3S, NOTE_D4N, NOTE_F4N, NOTE_B4N, NOTE_D4N, NOTE_F4N, NOTE_B4N,

	NOTE_E3N, NOTE_G3N, NOTE_C4N, NOTE_G4N, NOTE_C5N, NOTE_C4N, NOTE_G4N, NOTE_C5N, // measures 15-16, NOTE_notes 225-256
	NOTE_E3N, NOTE_G3N, NOTE_C4N, NOTE_G4N, NOTE_C5N, NOTE_C4N, NOTE_G4N, NOTE_C5N,
	NOTE_E3N, NOTE_F3N, NOTE_A3N, NOTE_C4N, NOTE_F4N, NOTE_A3N, NOTE_C4N, NOTE_F4N,
	NOTE_E3N, NOTE_F3N, NOTE_A3N, NOTE_C4N, NOTE_F4N, NOTE_A3N, NOTE_C4N, NOTE_F4N,

	NOTE_D3N, NOTE_F3N, NOTE_A3N, NOTE_C4N, NOTE_F4N, NOTE_A3N, NOTE_C4N, NOTE_F4N, // measures 17-18, NOTE_notes 257-288
	NOTE_D3N, NOTE_F3N, NOTE_A3N, NOTE_C4N, NOTE_F4N, NOTE_A3N, NOTE_C4N, NOTE_F4N,
	NOTE_G2N, NOTE_D3N, NOTE_G3N, NOTE_B3N, NOTE_F4N, NOTE_G3N, NOTE_B3N, NOTE_F4N,
	NOTE_G2N, NOTE_D3N, NOTE_G3N, NOTE_B3N, NOTE_F4N, NOTE_G3N, NOTE_B3N, NOTE_F4N,
	NOTE_C3N, NOTE_E3N, NOTE_G3N, NOTE_C4N, NOTE_E4N, NOTE_G3N, NOTE_C4N, NOTE_E4N, // measures 19-20, NOTE_notes 289-320
	NOTE_C3N, NOTE_E3N, NOTE_G3N, NOTE_C4N, NOTE_E4N, NOTE_G3N, NOTE_C4N, NOTE_E4N,
	NOTE_C3N, NOTE_G3N, NOTE_A3S, NOTE_C4N, NOTE_E4N, NOTE_A3S, NOTE_C4N, NOTE_E4N,
	NOTE_C3N, NOTE_G3N, NOTE_A3S, NOTE_C4N, NOTE_E4N, NOTE_A3S, NOTE_C4N, NOTE_E4N,
	NOTE_F2N, NOTE_F3N, NOTE_A3N, NOTE_C4N, NOTE_E4N, NOTE_A3N, NOTE_C4N, NOTE_E4N, // measures 21-22, NOTE_notes 321-352
	NOTE_F2N, NOTE_F3N, NOTE_A3N, NOTE_C4N, NOTE_E4N, NOTE_A3N, NOTE_C4N, NOTE_E4N,
	NOTE_F2S, NOTE_C3N, NOTE_A3N, NOTE_C4N, NOTE_D4S, NOTE_A3N, NOTE_C4N, NOTE_D4S,
	NOTE_F2S, NOTE_C3N, NOTE_A3N, NOTE_C4N, NOTE_D4S, NOTE_A3N, NOTE_C4N, NOTE_D4S,
	NOTE_G2S, NOTE_F3N, NOTE_B3N, NOTE_C4N, NOTE_D4N, NOTE_B3N, NOTE_C4N, NOTE_D4N, // measures 23-24, NOTE_notes 353-384
	NOTE_G2S, NOTE_F3N, NOTE_B3N, NOTE_C4N, NOTE_D4N, NOTE_B3N, NOTE_C4N, NOTE_D4N,
	NOTE_G2N, NOTE_F3N, NOTE_G3N, NOTE_B3N, NOTE_D4N, NOTE_G3N, NOTE_B3N, NOTE_D4N,
	NOTE_G2N, NOTE_F3N, NOTE_G3N, NOTE_B3N, NOTE_D4N, NOTE_G3N, NOTE_B3N, NOTE_D4N,

	NOTE_G2N, NOTE_E3N, NOTE_G3N, NOTE_C4N, NOTE_E4N, NOTE_G3N, NOTE_C4N, NOTE_E4N, // meaures 25-26, NOTE_notes 385-416
	NOTE_G2N, NOTE_E3N, NOTE_G3N, NOTE_C4N, NOTE_E4N, NOTE_G3N, NOTE_C4N, NOTE_E4N,
	NOTE_G2N, NOTE_D3N, NOTE_G3N, NOTE_C4N, NOTE_F4N, NOTE_G3N, NOTE_C4N, NOTE_F4N,
	NOTE_G2N, NOTE_D3N, NOTE_G3N, NOTE_C4N, NOTE_F4N, NOTE_G3N, NOTE_C4N, NOTE_F4N,
	NOTE_G2N, NOTE_D3N, NOTE_G3N, NOTE_B3N, NOTE_F4N, NOTE_G3N, NOTE_B3N, NOTE_F4N, // measures 27-28, NOTE_notes 417-448
	NOTE_G2N, NOTE_D3N, NOTE_G3N, NOTE_B3N, NOTE_F4N, NOTE_G3N, NOTE_B3N, NOTE_F4N,
	NOTE_G2N, NOTE_D3S, NOTE_A3N, NOTE_C4N, NOTE_F4S, NOTE_A3N, NOTE_C4N, NOTE_F4S,
	NOTE_G2N, NOTE_D3S, NOTE_A3N, NOTE_C4N, NOTE_F4S, NOTE_A3N, NOTE_C4N, NOTE_F4S,
	NOTE_G2N, NOTE_E3N, NOTE_G3N, NOTE_C4N, NOTE_G4N, NOTE_G3N, NOTE_C4N, NOTE_G4N, // measures 29-30, NOTE_notes 449-480
	NOTE_G2N, NOTE_E3N, NOTE_G3N, NOTE_C4N, NOTE_G4N, NOTE_G3N, NOTE_C4N, NOTE_G4N,
	NOTE_G2N, NOTE_F3N, NOTE_G3N, NOTE_C4N, NOTE_F4N, NOTE_G3N, NOTE_C4N, NOTE_F4N,
	NOTE_G2N, NOTE_F3N, NOTE_G3N, NOTE_C4N, NOTE_F4N, NOTE_G3N, NOTE_C4N, NOTE_F4N,
	NOTE_G2N, NOTE_F3N, NOTE_G3N, NOTE_B3N, NOTE_F4N, NOTE_G3N, NOTE_B3N, NOTE_F4N, // measures 31-32, NOTE_notes 481-512
	NOTE_G2N, NOTE_F3N, NOTE_G3N, NOTE_B3N, NOTE_F4N, NOTE_G3N, NOTE_B3N, NOTE_F4N,
	NOTE_C2N, NOTE_C3N, NOTE_G3N, NOTE_A3S, NOTE_E4N, NOTE_G3N, NOTE_A3S, NOTE_E4N,
	NOTE_C2N, NOTE_C3N, NOTE_G3N, NOTE_A3S, NOTE_E4N, NOTE_G3N, NOTE_A3S, NOTE_E4N,
	NOTE_C2N, NOTE_C3N, NOTE_F3N, NOTE_A3N, NOTE_C4N, NOTE_F4N, NOTE_C4N, NOTE_A3N, // measures 33-34, NOTE_notes 513-544
	NOTE_C4N, NOTE_A3N, NOTE_F3N, NOTE_A3N, NOTE_F3N, NOTE_D3N, NOTE_F3N, NOTE_D3N,
	NOTE_C2N, NOTE_B2N, NOTE_G4N, NOTE_B4N, NOTE_D5N, NOTE_F5N, NOTE_D5N, NOTE_B4N,
	NOTE_D5N, NOTE_B4N, NOTE_G4N, NOTE_B4N, NOTE_D4N, NOTE_F4N, NOTE_E4N, NOTE_D4N,
};

// ----------------------------------------------------------------------------

#endif

// ----------------------------------------------------------------------------
